services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: otpuser
      POSTGRES_PASSWORD: otppass
      POSTGRES_DB: otpdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U otpuser -d otpdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: python -u -m uvicorn app:app --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: postgresql+psycopg2://otpuser:otppass@db:5432/otpdb

      JWT_SECRET: "your_jwt_secret"
      JWT_ALGORITHM: "HS256"
      PYTHONUNBUFFERED: 1
      DB_POOL_MAX_CONN: 2
      LOG_LEVEL: "debug"
    ports:
      - "8000:8000"

  test-integration:
    build: .
    depends_on:
      - app
    environment:
      BASE_URL: http://app:8000
    command: >
      sh -c "sleep 10 && pytest test_integration.py"